import { Code, ExternalLink, FileText } from "lucide-react"

export type ConnectorItem = {
  id: string
  composio_app?: string
  openclaw_tool?: string
  name: string
  icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }>
  color: string
  description: string
  actions: string[]
}

export type SoulConnectorCategory = {
  label: string
  description: string
  items: ConnectorItem[]
}

export const SOUL_CONNECTORS: Record<string, SoulConnectorCategory> = {
  documents: {
    label: "Documents & Instructions",
    description: "Static instructions, SOPs, guidelines",
    items: [
      {
        id: "googledocs",
        composio_app: "googledocs",
        name: "Google Docs",
        icon: FileText,
        color: "#4285F4",
        description: "SOPs, procedures, scripts",
        actions: ["GOOGLEDOCS_GET_DOCUMENT", "GOOGLEDOCS_SEARCH"],
      },
      {
        id: "notion",
        composio_app: "notion",
        name: "Notion",
        icon: FileText,
        color: "#000000",
        description: "Wiki pages, runbooks",
        actions: ["NOTION_GET_PAGE", "NOTION_SEARCH"],
      },
      {
        id: "confluence",
        composio_app: "confluence",
        name: "Confluence",
        icon: FileText,
        color: "#0052CC",
        description: "Enterprise documentation",
        actions: ["CONFLUENCE_GET_PAGE", "CONFLUENCE_SEARCH"],
      },
      {
        id: "github",
        composio_app: "github",
        name: "GitHub",
        icon: Code,
        color: "#181717",
        description: "Markdown files in repos",
        actions: ["GITHUB_GET_FILE_CONTENT", "GITHUB_SEARCH_CODE"],
      },
      {
        id: "dropbox",
        composio_app: "dropbox",
        name: "Dropbox",
        icon: FileText,
        color: "#0061FF",
        description: "Cloud storage files",
        actions: ["DROPBOX_GET_FILE", "DROPBOX_SEARCH"],
      },
    ],
  },
  liveData: {
    label: "Live Data Sources",
    description: "Real-time info: prices, inventory, availability",
    items: [
      {
        id: "googlesheets",
        composio_app: "googlesheets",
        name: "Google Sheets",
        icon: FileText,
        color: "#0F9D58",
        description: "Price lists, catalogs, schedules",
        actions: [
          "GOOGLESHEETS_GET_SPREADSHEET_DATA",
          "GOOGLESHEETS_LOOKUP_ROW",
        ],
      },
      {
        id: "airtable",
        composio_app: "airtable",
        name: "Airtable",
        icon: FileText,
        color: "#18BFFF",
        description: "Product database, inventory",
        actions: ["AIRTABLE_LIST_RECORDS", "AIRTABLE_GET_RECORD"],
      },
      {
        id: "coda",
        composio_app: "coda",
        name: "Coda",
        icon: FileText,
        color: "#F46A54",
        description: "Dynamic docs with formulas",
        actions: ["CODA_GET_ROWS", "CODA_GET_DOC"],
      },
      {
        id: "smartsheet",
        composio_app: "smartsheet",
        name: "Smartsheet",
        icon: FileText,
        color: "#0073EA",
        description: "Enterprise spreadsheets",
        actions: ["SMARTSHEET_GET_SHEET", "SMARTSHEET_SEARCH_ROWS"],
      },
    ],
  },
  crm: {
    label: "CRM & Customer Data",
    description: "Customer info, deals, interactions",
    items: [
      {
        id: "hubspot",
        composio_app: "hubspot",
        name: "HubSpot",
        icon: FileText,
        color: "#FF7A59",
        description: "Contacts, deals, properties",
        actions: ["HUBSPOT_GET_CONTACT", "HUBSPOT_GET_DEAL", "HUBSPOT_SEARCH"],
      },
      {
        id: "salesforce",
        composio_app: "salesforce",
        name: "Salesforce",
        icon: FileText,
        color: "#00A1E0",
        description: "Accounts, opportunities",
        actions: ["SALESFORCE_GET_ACCOUNT", "SALESFORCE_SEARCH_RECORDS"],
      },
      {
        id: "pipedrive",
        composio_app: "pipedrive",
        name: "Pipedrive",
        icon: FileText,
        color: "#1D1D1D",
        description: "Pipeline, activities",
        actions: ["PIPEDRIVE_GET_DEAL", "PIPEDRIVE_GET_PERSON"],
      },
      {
        id: "zohocrm",
        composio_app: "zohocrm",
        name: "Zoho CRM",
        icon: FileText,
        color: "#E42527",
        description: "Leads, contacts, deals",
        actions: ["ZOHOCRM_GET_RECORD", "ZOHOCRM_SEARCH"],
      },
      {
        id: "freshsales",
        composio_app: "freshsales",
        name: "Freshsales",
        icon: FileText,
        color: "#13AE86",
        description: "Sales CRM",
        actions: ["FRESHSALES_GET_CONTACT", "FRESHSALES_GET_DEAL"],
      },
    ],
  },
  databases: {
    label: "Databases & APIs",
    description: "Direct data queries (OpenClaw native tools)",
    items: [
      {
        id: "postgres",
        openclaw_tool: "database_query",
        name: "PostgreSQL",
        icon: Code,
        color: "#336791",
        description: "SQL queries for live data",
        actions: ["SQL_QUERY", "SQL_SCHEMA"],
      },
      {
        id: "mysql",
        openclaw_tool: "database_query",
        name: "MySQL",
        icon: Code,
        color: "#4479A1",
        description: "MySQL database queries",
        actions: ["SQL_QUERY"],
      },
      {
        id: "rest_api",
        openclaw_tool: "http_request",
        name: "REST API",
        icon: Code,
        color: "#6B7280",
        description: "Custom API endpoints",
        actions: ["HTTP_GET", "HTTP_POST"],
      },
      {
        id: "graphql",
        openclaw_tool: "graphql_query",
        name: "GraphQL",
        icon: Code,
        color: "#E535AB",
        description: "GraphQL queries",
        actions: ["GRAPHQL_QUERY"],
      },
      {
        id: "supabase",
        composio_app: "supabase",
        name: "Supabase",
        icon: Code,
        color: "#3ECF8E",
        description: "Postgres + API",
        actions: ["SUPABASE_SELECT", "SUPABASE_RPC"],
      },
    ],
  },
  web: {
    label: "Web & Public Sources",
    description: "Web scraping & feeds (OpenClaw native tools)",
    items: [
      {
        id: "webpage",
        openclaw_tool: "web_scrape",
        name: "Web Page",
        icon: ExternalLink,
        color: "#10B981",
        description: "Scrape any public URL",
        actions: ["SCRAPE_URL", "EXTRACT_TEXT"],
      },
      {
        id: "sitemap",
        openclaw_tool: "web_crawl",
        name: "Sitemap Crawl",
        icon: FileText,
        color: "#8B5CF6",
        description: "Crawl entire website",
        actions: ["CRAWL_SITEMAP", "INDEX_PAGES"],
      },
      {
        id: "rss",
        openclaw_tool: "rss_fetch",
        name: "RSS Feed",
        icon: FileText,
        color: "#F97316",
        description: "News, blogs, updates",
        actions: ["FETCH_RSS", "PARSE_FEED"],
      },
      {
        id: "youtube",
        composio_app: "youtube",
        name: "YouTube",
        icon: FileText,
        color: "#FF0000",
        description: "Video transcripts",
        actions: ["YOUTUBE_GET_TRANSCRIPT", "YOUTUBE_GET_VIDEO_INFO"],
      },
      {
        id: "twitter",
        composio_app: "twitter",
        name: "Twitter/X",
        icon: FileText,
        color: "#1DA1F2",
        description: "Tweets, threads",
        actions: ["TWITTER_GET_TWEETS", "TWITTER_SEARCH"],
      },
    ],
  },
  internal: {
    label: "Internal Systems",
    description: "Your company's internal tools",
    items: [
      {
        id: "sharepoint",
        composio_app: "sharepoint",
        name: "SharePoint",
        icon: FileText,
        color: "#038387",
        description: "Microsoft intranet",
        actions: ["SHAREPOINT_GET_FILE", "SHAREPOINT_SEARCH"],
      },
      {
        id: "jira",
        composio_app: "jira",
        name: "Jira",
        icon: FileText,
        color: "#0052CC",
        description: "Tickets, projects",
        actions: ["JIRA_GET_ISSUE", "JIRA_SEARCH", "JIRA_GET_PROJECT"],
      },
      {
        id: "asana",
        composio_app: "asana",
        name: "Asana",
        icon: FileText,
        color: "#F06A6A",
        description: "Tasks, projects",
        actions: ["ASANA_GET_TASK", "ASANA_SEARCH_TASKS"],
      },
      {
        id: "zendesk",
        composio_app: "zendesk",
        name: "Zendesk",
        icon: FileText,
        color: "#03363D",
        description: "Support tickets, FAQs",
        actions: ["ZENDESK_GET_TICKET", "ZENDESK_SEARCH_ARTICLES"],
      },
      {
        id: "intercom",
        composio_app: "intercom",
        name: "Intercom",
        icon: FileText,
        color: "#1F8DED",
        description: "Help center articles",
        actions: ["INTERCOM_GET_ARTICLE", "INTERCOM_SEARCH"],
      },
      {
        id: "linear",
        composio_app: "linear",
        name: "Linear",
        icon: FileText,
        color: "#5E6AD2",
        description: "Issue tracking",
        actions: ["LINEAR_GET_ISSUE", "LINEAR_SEARCH"],
      },
    ],
  },
  communication: {
    label: "Communication Channels",
    description: "Learn from team conversations",
    items: [
      {
        id: "slack",
        composio_app: "slack",
        name: "Slack",
        icon: FileText,
        color: "#4A154B",
        description: "Channel history, search",
        actions: ["SLACK_READ_CHANNEL", "SLACK_SEARCH_MESSAGES"],
      },
      {
        id: "gmail",
        composio_app: "gmail",
        name: "Gmail",
        icon: FileText,
        color: "#EA4335",
        description: "Email search, threads",
        actions: ["GMAIL_SEARCH", "GMAIL_GET_THREAD"],
      },
      {
        id: "outlook",
        composio_app: "outlook",
        name: "Outlook",
        icon: FileText,
        color: "#0078D4",
        description: "Email, calendar",
        actions: ["OUTLOOK_SEARCH_MAIL", "OUTLOOK_GET_EVENTS"],
      },
      {
        id: "discord",
        composio_app: "discord",
        name: "Discord",
        icon: FileText,
        color: "#5865F2",
        description: "Server messages",
        actions: ["DISCORD_GET_MESSAGES", "DISCORD_SEARCH"],
      },
      {
        id: "teams",
        composio_app: "microsoftteams",
        name: "MS Teams",
        icon: FileText,
        color: "#6264A7",
        description: "Team chats",
        actions: ["TEAMS_GET_MESSAGES", "TEAMS_SEARCH"],
      },
    ],
  },
  calendar: {
    label: "Calendar & Scheduling",
    description: "Availability, events, meetings",
    items: [
      {
        id: "googlecalendar",
        composio_app: "googlecalendar",
        name: "Google Calendar",
        icon: FileText,
        color: "#4285F4",
        description: "Events, availability",
        actions: [
          "GOOGLECALENDAR_GET_EVENTS",
          "GOOGLECALENDAR_CHECK_AVAILABILITY",
        ],
      },
      {
        id: "calendly",
        composio_app: "calendly",
        name: "Calendly",
        icon: FileText,
        color: "#006BFF",
        description: "Scheduling links",
        actions: ["CALENDLY_GET_SCHEDULED_EVENTS", "CALENDLY_GET_AVAILABILITY"],
      },
      {
        id: "cal",
        composio_app: "calcom",
        name: "Cal.com",
        icon: FileText,
        color: "#292929",
        description: "Open source scheduling",
        actions: ["CALCOM_GET_BOOKINGS", "CALCOM_GET_AVAILABILITY"],
      },
    ],
  },
}

export const getAllConnectors = () =>
  Object.values(SOUL_CONNECTORS).flatMap((c) => c.items)
